name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H 165.22.223.122 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh root@165.22.223.122 << 'EOF'
            cd /var/www/printage-jc-backend
            git pull origin main
            npm install
            pm2 restart all
          EOF
